### ISSUE TITLE
 Récupérer l'id des chapitres dans leur Nom.

### ISSUE THREAD

**Issue by MedouneSGB** [nouha404/manga_api#1]
Hey @nouha404 
J'ai quelques suggestions

![image](https://user-images.githubusercontent.com/40875400/199587093-08e06f75-c93d-48c1-a156-193ddabd12e7.png)

Il faudrait récupérer l'id des chapitres dans leur Nom.
Par exemple on a les chapitres 1053.5, 1053.6, 1053.7, 1053.8
l'id utilisé actuellement se base sur le nombre de chapitre.

**Comment by lamine2000** [comment]
Bonsoir, grand. Je voudrais aider sur cette issue... any indication (files to edit maybe) ?

**Comment by MedouneSGB** [comment]
Salut @lamine2000 vraiment désolé du retard.
Pourrais tu faire un script qui extrait l'ID depuis [one_piece_db.json](https://github.com/nouha404/manga_api/blob/main/one_piece_db.json).

**Comment by lamine2000** [comment]
Hi, j'ai fait un peu plus que ca dans ma [pull request:](https://github.com/nouha404/manga_api/pull/4)
-Code reformated
-Adressed performance issues, using builtin search methods
-Redesigned the database file structure
-Made chapters accessible by their number instead of their names
-Made the pages accessible by their number (without the image file extension, but can still contain non-number characters)

Disclaimer: Les chapitres dont le numero comporte un '.' n'ont pas ete pris en charge (will take care of it with some other improvements in another pul request)

**Comment by MedouneSGB** [comment]
Awesome 🚀✨
Nice Job guys !
